version: '3.9'

services:
  nb:
    build:
      context: .
      dockerfile: nb/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - argmax
    depends_on:
      - pg

  pg:
    image: pg/Dockerfile
    ports:
      - "5432:5432"
    networks:
      - argmax

networks:
  argmax:
    driver: bridge
