version: '3.9'

services:
  nb:
    build:
      context: .
      dockerfile: nb/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - argmax
    depends_on:
      - pg

  pg:
    build:
      context: .
      dockerfile: nb/Dockerfile
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: argmax
    networks:
      - argmax

networks:
  argmax:
    driver: bridge
