version: '3.9'

services:
  nb:
    build:
      context: nb
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - argmax
    depends_on:
      - emb

  emb:
    build:
      context: emb
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - argmax
    depends_on:
      - pg

  pg:
    build:
      context: pg
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: argmax
    networks:
      - argmax

networks:
  argmax:
    driver: bridge
